#!/bin/bash

# Pass specfile location here

path=$(realpath "$1")

if grep "BuildRequires" "$path"; then
    pkexec dnf builddep "$path"
fi

rpmbuild -bb "$path" --define "_tmppath $PWD" --define "_topdir $PWD" --define "_sourcedir $PWD" --define "_rpmdir $PWD" --undefine=_disable_source_fetch
